apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-proxy
  name: nginx-proxy
  annotations: 
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::{{id}}:{{certificate-information}}
#    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
#  - name: https
#    protocol: TCP
#    port: 443
#    targetPort: 80
  selector:
    app: nginx-proxy
  type: LoadBalancer